type: specs.intershop.com/v1beta/migrate
migrator: com.intershop.customization.migration.pfconfigurationfs.MigrateConfigResources
message: "feat: configuration resources '*.resource' files into '*.properties'"
